# Generated by Django 4.2.2 on 2023-06-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_article_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('done', 'Сделано')], max_length=50, verbose_name='Название')),
                ('author', models.CharField(default='Неизвестный', max_length=50, verbose_name='Автор')),
                ('description', models.TextField(max_length=2000, verbose_name='Контент')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задача',
                'db_table': 'tasks',
            },
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
