# Generated by Django 4.2.2 on 2023-07-07 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='data_field',
        ),
    ]
