# Generated by Django 4.2.2 on 2023-07-11 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_task_type_task_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='type',
        ),
    ]
