# Generated by Django 4.2.2 on 2023-07-11 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_remove_task_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_types', to='webapp.tasks', verbose_name='Задача')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_tasks', to='webapp.type', verbose_name='Тип')),
            ],
        ),
        migrations.AddField(
            model_name='tasks',
            name='type',
            field=models.ManyToManyField(blank=True, related_name='tasks', through='webapp.TaskType', to='webapp.type'),
        ),
    ]
