# Generated by Django 4.2.2 on 2023-06-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_task_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='author',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='task',
            name='data_field',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='task',
            name='detailed_description',
            field=models.TextField(blank=True, default=None, max_length=2000, null=True, verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Описание'),
        ),
    ]
